name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Geração da Animação Snake
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: marlonbatista
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Listar arquivos para depuração
      - name: List files in dist directory
        run: |
          echo "Listing files in dist directory:"
          ls -la dist

      # Publicar no GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
